"""Language constants for ATLAS by EWU."""

LANGUAGE_PL = "pl"
LANGUAGE_UK = "uk"
LANGUAGE_RU = "ru"
LANGUAGE_EN = "en"
LANGUAGE_DE = "de"
LANGUAGE_ES = "es"
LANGUAGE_PT = "pt"

SUPPORTED_LANGUAGES = (
    LANGUAGE_PL,
    LANGUAGE_UK,
    LANGUAGE_RU,
    LANGUAGE_EN,
    LANGUAGE_DE,
    LANGUAGE_ES,
    LANGUAGE_PT,
)

DEFAULT_LANGUAGE = LANGUAGE_PL
