"""Colosseum MVP workflows for credentials, escrow, privacy, and demo state.

The module keeps private personal data off-chain. Devnet records store only
technical hashes and explorer-ready signatures generated by the demo adapter.
"""

from __future__ import annotations

import hashlib
import os
from typing import Any

from core.models import ActivityEvent, Candidate, Employer, Vacancy, new_id, utc_now_iso
from database.json_database import JsonDatabase
from database.repositories import ActivityRepository, CandidateRepository, EmployerRepository, VacancyRepository


COL_CREDENTIALS = "colosseum_credentials"
COL_ESCROWS = "colosseum_escrows"
COL_DEMO_STATE = "colosseum_demo_state"
COL_PRIVACY_REQUESTS = "colosseum_privacy_requests"

ROLE_PERMISSIONS = {
    "candidate": {"credential:request", "privacy:self"},
    "employer": {"escrow:create", "escrow:fund", "escrow:approve", "escrow:release", "match:view"},
    "issuer": {"credential:verify", "credential:reject", "credential:revoke", "credential:anchor"},
    "recruiter": {"credential:view", "escrow:view"},
    "admin": {"*"},
}


class ColosseumMVPService:
    def __init__(
        self,
        database: JsonDatabase,
        candidates: CandidateRepository,
        employers: EmployerRepository,
        vacancies: VacancyRepository,
        activity: ActivityRepository,
    ) -> None:
        self.database = database
        self.candidates = candidates
        self.employers = employers
        self.vacancies = vacancies
        self.activity = activity

    def demo_status(self) -> dict[str, Any]:
        state = self.database.get(COL_DEMO_STATE, "default") or {}
        return {
            "demo_mode": _env_bool("DEMO_MODE", True),
            "seeded": bool(state.get("seeded")),
            "seeded_at": state.get("seeded_at"),
            "candidate_id": state.get("candidate_id"),
            "employer_id": state.get("employer_id"),
            "vacancy_id": state.get("vacancy_id"),
            "credential_id": state.get("credential_id"),
            "escrow_id": state.get("escrow_id"),
            "flow": ["profile", "verify", "match", "hire", "settle"],
        }

    def reset_demo(self, actor_id: str = "demo") -> dict[str, Any]:
        for collection in (COL_CREDENTIALS, COL_ESCROWS, COL_PRIVACY_REQUESTS):
            for item in self.database.list(collection):
                item_id = str(item.get("id"))
                if item.get("demo") and item_id:
                    item["status"] = "archived"
                    item["archived_at"] = utc_now_iso()
                    self.database.update(collection, item_id, item)
        self.database.update(COL_DEMO_STATE, "default", {"seeded": False, "reset_at": utc_now_iso()})
        self._audit(actor_id, "demo", "default", "demo_reset", new_value="reset")
        return {"status": "ok", "demo": self.demo_status()}

    def seed_demo(self, actor_id: str = "demo") -> dict[str, Any]:
        candidate = _first_or_create_candidate(self.candidates)
        employer = _first_or_create_employer(self.employers)
        vacancy = _first_or_create_vacancy(self.vacancies, employer.id)
        credential = self.request_credential(
            {
                "candidate_id": candidate.id,
                "issuer_id": "issuer-demo",
                "credential_type": "professional_certificate",
                "title": "MIG/MAG Welder Certificate",
                "source_document_hash": _hash({"candidate": candidate.id, "title": "MIG/MAG Welder Certificate"}),
                "evidence": {"document": "demo-cv.pdf", "status": "candidate_confirmed"},
                "demo": True,
            },
            actor_id=actor_id,
            role="candidate",
        )
        credential = self.verify_credential(credential["id"], {"note": "Issuer confirmed demo credential"}, actor_id, "issuer")
        credential = self.anchor_credential(credential["id"], actor_id, "issuer")
        escrow = self.create_escrow(
            {
                "employer_id": employer.id,
                "recruiter_id": "recruiter-demo",
                "partner_id_optional": "partner-demo",
                "candidate_id": candidate.id,
                "job_id": vacancy.id,
                "total_amount": 100,
                "currency_or_token": "DEVNET_SOL",
                "recruiter_share": 70,
                "partner_share": 10,
                "platform_share": 20,
                "milestone_type": "candidate_started_work",
                "dispute_window_hours": 72,
                "refund_condition": "Milestone not approved before dispute window",
                "demo": True,
            },
            actor_id=actor_id,
            role="employer",
        )
        self.database.update(
            COL_DEMO_STATE,
            "default",
            {
                "seeded": True,
                "seeded_at": utc_now_iso(),
                "candidate_id": candidate.id,
                "employer_id": employer.id,
                "vacancy_id": vacancy.id,
                "credential_id": credential["id"],
                "escrow_id": escrow["id"],
            },
        )
        self._audit(actor_id, "demo", "default", "demo_seed", new_value="seeded")
        return {
            "status": "ok",
            "candidate": candidate.to_dict(),
            "employer": employer.to_dict(),
            "vacancy": vacancy.to_dict(),
            "credential": credential,
            "escrow": escrow,
            "demo": self.demo_status(),
        }

    def request_credential(self, payload: dict[str, Any], actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "credential:request")
        candidate_id = str(payload.get("candidate_id") or "").strip()
        if not self.candidates.get(candidate_id):
            raise ValueError("Candidate not found")
        credential = {
            "id": new_id("CRD"),
            "candidate_id": candidate_id,
            "issuer_id": str(payload.get("issuer_id") or "issuer-demo"),
            "credential_type": str(payload.get("credential_type") or "professional_certificate"),
            "title": str(payload.get("title") or "Professional credential"),
            "source_document_hash": str(payload.get("source_document_hash") or _hash(payload.get("evidence") or {})),
            "credential_hash": "",
            "status": "pending",
            "issued_at": None,
            "revoked_at": None,
            "solana_signature": "",
            "solana_account": "",
            "solana_cluster": _cluster(),
            "program_id": os.getenv("SOLANA_CREDENTIAL_PROGRAM_ID", "demo-credential-program"),
            "explorer_url": "",
            "human_review_required": True,
            "ai_decision": "not_allowed",
            "evidence": payload.get("evidence") or {},
            "demo": bool(payload.get("demo")),
            "created_at": utc_now_iso(),
            "updated_at": utc_now_iso(),
        }
        self.database.insert(COL_CREDENTIALS, credential["id"], credential)
        self._audit(actor_id, "credential", credential["id"], "credential_requested", new_value="pending")
        return credential

    def list_credentials(self, role: str, actor_id: str = "") -> list[dict[str, Any]]:
        _require(role, "credential:view" if role in {"issuer", "recruiter"} else "credential:request")
        credentials = self.database.list(COL_CREDENTIALS)
        if role == "candidate":
            candidate_ids = {item.id for item in self.candidates.list() if item.user_id == actor_id or item.id == actor_id}
            return [item for item in credentials if item.get("candidate_id") in candidate_ids]
        return [item for item in credentials if item.get("status") != "archived"]

    def get_credential(self, credential_id: str) -> dict[str, Any]:
        credential = self.database.get(COL_CREDENTIALS, credential_id)
        if not credential or credential.get("status") == "archived":
            raise ValueError("Credential not found")
        return credential

    def verify_credential(self, credential_id: str, payload: dict[str, Any], actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "credential:verify")
        credential = self.get_credential(credential_id)
        if credential["status"] != "pending":
            raise ValueError("Only pending credentials can be verified")
        credential["status"] = "verified"
        credential["issued_at"] = utc_now_iso()
        credential["credential_hash"] = _hash(
            {
                "credential_id": credential["id"],
                "candidate_id": credential["candidate_id"],
                "issuer_id": credential["issuer_id"],
                "source_document_hash": credential["source_document_hash"],
                "issued_at": credential["issued_at"],
            }
        )
        credential["verification_note"] = str(payload.get("note") or "")
        credential["updated_at"] = utc_now_iso()
        self.database.update(COL_CREDENTIALS, credential_id, credential)
        self._audit(actor_id, "credential", credential_id, "credential_verified", old_value="pending", new_value="verified")
        return credential

    def reject_credential(self, credential_id: str, payload: dict[str, Any], actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "credential:reject")
        credential = self.get_credential(credential_id)
        if credential["status"] not in {"pending", "verified"}:
            raise ValueError("Credential cannot be rejected from current status")
        old = credential["status"]
        credential["status"] = "rejected"
        credential["rejection_reason"] = str(payload.get("reason") or "Rejected by issuer")
        credential["updated_at"] = utc_now_iso()
        self.database.update(COL_CREDENTIALS, credential_id, credential)
        self._audit(actor_id, "credential", credential_id, "credential_rejected", old_value=old, new_value="rejected")
        return credential

    def revoke_credential(self, credential_id: str, payload: dict[str, Any], actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "credential:revoke")
        credential = self.get_credential(credential_id)
        if credential["status"] != "verified":
            raise ValueError("Only verified credentials can be revoked")
        credential["status"] = "revoked"
        credential["revoked_at"] = utc_now_iso()
        credential["revocation_reason"] = str(payload.get("reason") or "Revoked by issuer")
        credential["updated_at"] = utc_now_iso()
        self.database.update(COL_CREDENTIALS, credential_id, credential)
        self._audit(actor_id, "credential", credential_id, "credential_revoked", old_value="verified", new_value="revoked")
        return credential

    def anchor_credential(self, credential_id: str, actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "credential:anchor")
        credential = self.get_credential(credential_id)
        if credential["status"] != "verified":
            raise ValueError("Only verified credentials can be anchored")
        if not credential.get("credential_hash"):
            raise ValueError("Credential hash missing")
        proof = _devnet_proof("credential", credential["credential_hash"])
        credential.update(proof)
        credential["updated_at"] = utc_now_iso()
        self.database.update(COL_CREDENTIALS, credential_id, credential)
        self._audit(actor_id, "credential", credential_id, "credential_anchored", new_value=credential["solana_signature"])
        return credential

    def create_escrow(self, payload: dict[str, Any], actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "escrow:create")
        total = _amount(payload.get("total_amount"))
        shares = {
            "recruiter_share": _amount(payload.get("recruiter_share")),
            "partner_share": _amount(payload.get("partner_share")),
            "platform_share": _amount(payload.get("platform_share")),
        }
        if round(sum(shares.values()), 8) != round(total, 8):
            raise ValueError("Escrow shares must equal total_amount")
        max_demo = _amount(os.getenv("DEMO_ESCROW_MAX_AMOUNT", "1000"))
        if _env_bool("DEMO_MODE", True) and total > max_demo:
            raise ValueError("Demo escrow amount exceeds DEMO_ESCROW_MAX_AMOUNT")
        escrow_hash = _hash({**payload, "created_by": actor_id, "pii": "excluded"})
        proof = _devnet_proof("escrow-create", escrow_hash)
        escrow = {
            "id": new_id("ESC"),
            "employer_id": str(payload.get("employer_id") or ""),
            "recruiter_id": str(payload.get("recruiter_id") or ""),
            "partner_id_optional": str(payload.get("partner_id_optional") or ""),
            "candidate_id": str(payload.get("candidate_id") or ""),
            "job_id": str(payload.get("job_id") or ""),
            "total_amount": total,
            "currency_or_token": str(payload.get("currency_or_token") or "DEVNET_SOL"),
            **shares,
            "milestone_type": str(payload.get("milestone_type") or "candidate_started_work"),
            "milestone_status": "pending",
            "dispute_window_hours": int(payload.get("dispute_window_hours") or 72),
            "refund_condition": str(payload.get("refund_condition") or "Milestone not approved"),
            "status": "created",
            "solana_escrow_account": proof["solana_account"],
            "create_signature": proof["solana_signature"],
            "release_signature": "",
            "create_explorer_url": proof["explorer_url"],
            "release_explorer_url": "",
            "solana_cluster": _cluster(),
            "human_approval_required": True,
            "ai_release_allowed": False,
            "demo": bool(payload.get("demo")),
            "created_at": utc_now_iso(),
            "released_at": None,
        }
        self.database.insert(COL_ESCROWS, escrow["id"], escrow)
        self._audit(actor_id, "escrow", escrow["id"], "escrow_created", new_value="created")
        return escrow

    def list_escrows(self, role: str) -> list[dict[str, Any]]:
        _require(role, "escrow:view" if role == "recruiter" else "escrow:create")
        return [item for item in self.database.list(COL_ESCROWS) if item.get("status") != "archived"]

    def get_escrow(self, escrow_id: str) -> dict[str, Any]:
        escrow = self.database.get(COL_ESCROWS, escrow_id)
        if not escrow or escrow.get("status") == "archived":
            raise ValueError("Escrow not found")
        return escrow

    def fund_escrow(self, escrow_id: str, actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "escrow:fund")
        escrow = self.get_escrow(escrow_id)
        if escrow["status"] != "created":
            raise ValueError("Only created escrows can be funded")
        escrow["status"] = "funded"
        escrow["funded_at"] = utc_now_iso()
        self.database.update(COL_ESCROWS, escrow_id, escrow)
        self._audit(actor_id, "escrow", escrow_id, "escrow_funded", old_value="created", new_value="funded")
        return escrow

    def approve_milestone(self, escrow_id: str, payload: dict[str, Any], actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "escrow:approve")
        escrow = self.get_escrow(escrow_id)
        if escrow["status"] != "funded":
            raise ValueError("Escrow must be funded before milestone approval")
        escrow["milestone_status"] = "approved"
        escrow["milestone_approved_at"] = utc_now_iso()
        escrow["milestone_note"] = str(payload.get("note") or "")
        escrow["status"] = "milestone_approved"
        self.database.update(COL_ESCROWS, escrow_id, escrow)
        self._audit(actor_id, "escrow", escrow_id, "milestone_approved", new_value="approved")
        return escrow

    def release_escrow(self, escrow_id: str, actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "escrow:release")
        escrow = self.get_escrow(escrow_id)
        if escrow["status"] == "released":
            raise ValueError("Escrow already released")
        if escrow["status"] != "milestone_approved":
            raise ValueError("Milestone must be explicitly approved before release")
        proof = _devnet_proof("escrow-release", _hash(escrow))
        escrow["status"] = "released"
        escrow["released_at"] = utc_now_iso()
        escrow["release_signature"] = proof["solana_signature"]
        escrow["release_explorer_url"] = proof["explorer_url"]
        escrow["payouts"] = [
            {"recipient": "recruiter", "amount": escrow["recruiter_share"]},
            {"recipient": "partner", "amount": escrow["partner_share"]},
            {"recipient": "platform", "amount": escrow["platform_share"]},
        ]
        self.database.update(COL_ESCROWS, escrow_id, escrow)
        self._audit(actor_id, "escrow", escrow_id, "escrow_released", new_value=escrow["release_signature"])
        return escrow

    def dispute_escrow(self, escrow_id: str, payload: dict[str, Any], actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "escrow:approve")
        escrow = self.get_escrow(escrow_id)
        if escrow["status"] == "released":
            raise ValueError("Released escrow cannot be disputed")
        escrow["status"] = "disputed"
        escrow["dispute_reason"] = str(payload.get("reason") or "Dispute opened")
        self.database.update(COL_ESCROWS, escrow_id, escrow)
        self._audit(actor_id, "escrow", escrow_id, "escrow_disputed", new_value="disputed")
        return escrow

    def refund_escrow(self, escrow_id: str, actor_id: str, role: str) -> dict[str, Any]:
        _require(role, "escrow:approve")
        escrow = self.get_escrow(escrow_id)
        if escrow["status"] == "released":
            raise ValueError("Released escrow cannot be refunded")
        escrow["status"] = "refunded"
        escrow["refunded_at"] = utc_now_iso()
        self.database.update(COL_ESCROWS, escrow_id, escrow)
        self._audit(actor_id, "escrow", escrow_id, "escrow_refunded", new_value="refunded")
        return escrow

    def privacy_delete_request(self, subject_id: str, contact: str = "", note: str = "") -> dict[str, Any]:
        request = {
            "id": new_id("PRV"),
            "subject_id": subject_id,
            "request_type": "delete",
            "contact": contact or subject_id,
            "status": "requested",
            "note": note,
            "created_at": utc_now_iso(),
            "physical_deletion": "queued_for_background_job",
        }
        self.database.insert(COL_PRIVACY_REQUESTS, request["id"], request)
        self._audit(subject_id, "privacy", request["id"], "delete_requested", new_value="requested")
        return request

    def privacy_revoke_consent(self, subject_id: str, consent_type: str, reason: str = "") -> dict[str, Any]:
        request = {
            "id": new_id("PRV"),
            "subject_id": subject_id,
            "request_type": "consent_withdrawal",
            "consent_type": consent_type,
            "status": "completed",
            "reason": reason,
            "created_at": utc_now_iso(),
        }
        self.database.insert(COL_PRIVACY_REQUESTS, request["id"], request)
        self._audit(subject_id, "privacy", request["id"], "consent_revoked", new_value=consent_type)
        return request

    def _audit(
        self,
        actor_id: str,
        entity_type: str,
        entity_id: str,
        action: str,
        old_value: str | None = None,
        new_value: str | None = None,
    ) -> None:
        self.activity.add(
            ActivityEvent(
                entity_type=entity_type,
                entity_id=entity_id,
                action=action,
                old_value=old_value,
                new_value=new_value,
                actor_id=actor_id,
                metadata={"colosseum_mvp": True},
            )
        )


def _first_or_create_candidate(repository: CandidateRepository) -> Candidate:
    for candidate in repository.list():
        if candidate.email == "candidate@demo.atlas" or candidate.metadata.get("demo"):
            return candidate
    return repository.add(
        Candidate(
            first_name="Demo",
            last_name="Candidate",
            email="candidate@demo.atlas",
            phone="+48000000000",
            country_code="UA",
            profession_code="welder",
            languages=["uk", "pl", "en"],
            years_of_experience=6,
            user_id="candidate-demo",
            documents=["cv", "mig_mag_certificate"],
            metadata={
                "demo": True,
                "skills": ["mig", "mag", "technical drawing", "safety"],
                "desired_country_code": "PL",
                "work_authorization": ["pl"],
                "availability": "immediate",
            },
        )
    )


def _first_or_create_employer(repository: EmployerRepository) -> Employer:
    for employer in repository.list():
        if employer.contact_email == "employer@demo.atlas" or employer.metadata.get("demo"):
            return employer
    return repository.add(
        Employer(
            company_name="ATLAS Demo Steel",
            contact_email="employer@demo.atlas",
            contact_phone="+48111000000",
            country_code="PL",
            industry="manufacturing",
            verified=True,
            metadata={"demo": True},
        )
    )


def _first_or_create_vacancy(repository: VacancyRepository, employer_id: str) -> Vacancy:
    for vacancy in repository.list():
        if vacancy.metadata.get("demo"):
            return vacancy
    return repository.add(
        Vacancy(
            employer_id=employer_id,
            title="MIG/MAG Welder",
            country_code="PL",
            profession_code="welder",
            salary_min=5800,
            salary_max=7200,
            currency="PLN",
            required_languages=["pl"],
            required_documents=["cv", "mig_mag_certificate"],
            location="Poznan",
            metadata={
                "demo": True,
                "recruitment": {
                    "title": "MIG/MAG Welder",
                    "requirements": [
                        {"type": "skill", "label": "mig"},
                        {"type": "skill", "label": "mag"},
                        {"type": "skill", "label": "technical drawing"},
                        {"type": "certificate", "label": "mig_mag_certificate"},
                    ],
                    "languageRequirements": [{"language": "pl", "level": "B1"}],
                    "experienceMinimumYears": 3,
                    "employmentTypes": ["employment_contract"],
                    "workAuthorizationRequirements": ["pl"],
                },
            },
        )
    )


def _require(role: str, permission: str) -> None:
    normalized = (role or "candidate").strip().lower()
    permissions = ROLE_PERMISSIONS.get(normalized, set())
    if "*" in permissions or permission in permissions:
        return
    raise PermissionError(f"Role {normalized} cannot perform {permission}")


def _devnet_proof(kind: str, payload_hash: str) -> dict[str, str]:
    signature = _hash({"kind": kind, "payload_hash": payload_hash, "cluster": _cluster()})[:88]
    account = _hash({"account": kind, "payload_hash": payload_hash})[:44]
    return {
        "solana_signature": signature,
        "solana_account": account,
        "solana_cluster": _cluster(),
        "explorer_url": f"https://explorer.solana.com/tx/{signature}?cluster={_cluster()}",
    }


def _cluster() -> str:
    return os.getenv("SOLANA_CLUSTER", "devnet")


def _hash(value: Any) -> str:
    return hashlib.sha256(str(value).encode("utf-8")).hexdigest()


def _amount(value: Any) -> float:
    try:
        amount = float(value)
    except (TypeError, ValueError):
        raise ValueError("Amount must be numeric") from None
    if amount < 0:
        raise ValueError("Amount cannot be negative")
    return amount


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}
